// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubmszcuyzegqvgfnplgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVibXN6Y3V5emVncXZnZm5wbGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTQ2MjYsImV4cCI6MjA2OTYzMDYyNn0.KXGFDBXAOEZwSaO6fUg6aXq5FMDqwTTabCMDN8-ypaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});